name: Build docker image

on:
  # schedule:
  #   - cron: '44 0 * * *'
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  # REGISTRY: docker.io
  # github.repository as <account>/<repo>
  GO_VERSION:           "1.23"
  IMAGE_NAME:           ghcr.io/${{ github.repository }}
  DEPLOY_OS_LIST:       linux
  BUILD_GOAMD64_LIST:   1 2 3 4
  DEPLOY_ARCH_LIST:     amd64 arm64 arm
  BUILD_GOARM_LIST:     6 7
  DEPLOY_COMMIT_NUMBER: ${{ github.sha }}
  DEPLOY_TAG_VALUE:     ${{ github.event.workflow_run.head_branch }}
  APP_BUILD_TAGS:       allstreams,fsloader,dbloader,postgres,migrate,consul,etcd,htmltemplates,jaeger
  BUILD_PLATFORMS:      linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm64/v8


jobs:
  build:
    # Temporarily disabled until switch process in production
    # if: startsWith(github.event.workflow_run.head_branch, 'v')

    runs-on: ubuntu-latest
    # environment: "docker hub"

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          submodules: true

      - name: Get Tag or Commit SHA
        id: get_tag
        run: |
          # Attempt to get the tag name for the current commit
          TAG=$(git describe --tags --exact-match 2>/dev/null || echo $GITHUB_SHA)
          echo "DEPLOY_TAG_VALUE=${TAG}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ~${{ env.GO_VERSION }}

      - name: Setup Golang caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
            ${{ runner.os }}-

      - name: Build app
        run: make build

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image of the service
        id: build-and-push-service
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/production/Dockerfile
          platforms: ${{ env.BUILD_PLATFORMS }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.DEPLOY_TAG_VALUE }}
            ${{ env.IMAGE_NAME }}:latest
