version: '3.7'

services:
  # docker run --rm -it --label=service.name=jaeger -p 6831:6831/udp -p 16686:16686 jaegertracing/all-in-one:latest
  tracer:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    labels:
      - service.name=jaeger
  
  nats:
    image: nats
    restart: always
    expose:
      - "4222"
    labels:
      - service.name=nats

  sspserver:
    build: .
    ports:
      - "7077:8080"
    command: >
      go run -tags="fs allplatform"
      /project/sspserver/cmd/sspserver/main.go --debug=1
      --config=/project/sspserver/cmd/sspserver/configs/main.yml
    environment:
      DEBUG: "true"
      GOPATH: /project/.cache
      ADSTORAGE_CONNECTION: fs:/project/sspserver/cmd/sspserver/configs/
      EVENTSTREAM_EVENT_QUEUE_CONNECTION: nats://nats:4222
      EVENTSTREAM_USERINFO_QUEUE_CONNECTION: nats://nats:4222
      EVENTSTREAM_WINS_QUEUE_CONNECTION: nats://nats:4222
      JAEGER_AGENT_HOST: tracer
    depends_on:
      - nats
      - tracer
    volumes:
      - ../../:/project
    labels:
      - service.name=sspserver
