services:
  # docker run --rm -it --label=service.name=jaeger -p 6831:6831/udp -p 16686:16686 jaegertracing/all-in-one:latest
  # tracer:
  #   image: jaegertracing/all-in-one:latest
  #   ports:
  #     - "16686:16686"
  
  # nats:
  #   image: nats
  #   restart: always
  #   expose:
  #     - "4222"

  redis:
    restart: always
    image: redis:latest

  jssdk:
    image: ssp-project/jssdk
    ports:
      - "${DOCKER_JSSDK_HTTP_PORT}:8080"

  zookeeper:
    restart: always
    image: zookeeper:3.7
    container_name: zookeeper
    hostname: zookeeper
    volumes:
      - "zookeeper:/data"
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  clickhouse-server:
    user: root
    restart: on-failure
    image: clickhouse/clickhouse-server
    hostname: clickhouse-server
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - "./clickhouse/config.xml:/etc/clickhouse-server/config.xml:ro"
      - "./clickhouse/conf.d:/etc/clickhouse-server/conf.d:ro"
      - "clickhouse:/clickhouse/"
    # ulimit:
    #   nofile:
    #     soft: 262144
    #     hard: 262144

  database:
    restart: always
    image: postgres:16
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_INITDB_ARGS: ${POSTGRES_INITDB_ARGS}

  eventstream:
    image: geniusrabbit/eventstream:latest
    restart: always
    pull_policy: always
    depends_on: [redis, clickhouse-server]
    healthcheck:
      test: ["CMD", "/curl", "-f", "http://127.0.0.1:6060/health-check"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 40s
    env_file: ../../.env
    volumes:
      - ../eventstream.hcl:/config.hcl
    environment:
      - SERVER_PROFILE_MODE=net
      - SERVER_PROFILE_LISTEN=:6060

  sspserver:
    image: ssp-project/sspserver
    ports:
      - "${DOCKER_SERVER_HTTP_PORT}:8080"
      - "${DOCKER_SERVER_PROFILE_PORT}:8082"
    env_file:
      - ../../.env
    depends_on:
      - redis
      - eventstream
      # - jssdk
    volumes:
      - ../../:/project

volumes:
  clickhouse:
    driver: local
  zookeeper:
    driver: local
  pgdata:
    driver: local
