version: '3.7'

services:
  # docker run --rm -it --label=service.name=jaeger -p 6831:6831/udp -p 16686:16686 jaegertracing/all-in-one:latest
  tracer:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
  
  nats:
    image: nats
    restart: always
    expose:
      - "4222"
    labels:
      - service.name=nats

  sspserver:
    image: rtb/sspserver
    ports:
      - "7077:8080"
      - "7079:8082"
    env_file:
      - ../../.env
    depends_on:
      - nats
      - tracer
    volumes:
      - ../../:/project
    environment:
      ADSTORAGE_CONNECTION: fs:/data/
