// Code generated by qtc from "ad_banner.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/ad_banner.qtpl:2
package templates

//line templates/ad_banner.qtpl:2
import (
	"geniusrabbit.dev/sspserver/internal/adsource"
)

//line templates/ad_banner.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/ad_banner.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/ad_banner.qtpl:7
func streamadRenderBanner(qw422016 *qt422016.Writer, resp adsource.Responser, it adsource.ResponserItem) {
//line templates/ad_banner.qtpl:9
	urlStr := URLGen.MustClickURL(it, resp)
	asset := it.MainAsset()
	format := it.Format()

//line templates/ad_banner.qtpl:13
	if asset.IsImage() {
//line templates/ad_banner.qtpl:13
		qw422016.N().S(`<a href="`)
//line templates/ad_banner.qtpl:14
		qw422016.N().S(urlStr)
//line templates/ad_banner.qtpl:14
		qw422016.N().S(`" target="_blank"><img src="`)
//line templates/ad_banner.qtpl:14
		qw422016.N().S(asset.Path)
//line templates/ad_banner.qtpl:14
		qw422016.N().S(`"onload="u`)
//line templates/ad_banner.qtpl:15
		qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:15
		qw422016.N().S(`(1);v`)
//line templates/ad_banner.qtpl:15
		qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:15
		qw422016.N().S(`(1)"onerror="u`)
//line templates/ad_banner.qtpl:16
		qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:16
		qw422016.N().S(`(0);v`)
//line templates/ad_banner.qtpl:16
		qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:16
		qw422016.N().S(`(0)"`)
//line templates/ad_banner.qtpl:17
		if format.IsFixed() {
//line templates/ad_banner.qtpl:17
			qw422016.N().S(`width="`)
//line templates/ad_banner.qtpl:18
			qw422016.N().D(format.Width)
//line templates/ad_banner.qtpl:18
			qw422016.N().S(`" height="`)
//line templates/ad_banner.qtpl:18
			qw422016.N().D(format.Height)
//line templates/ad_banner.qtpl:18
			qw422016.N().S(`"`)
//line templates/ad_banner.qtpl:19
		}
//line templates/ad_banner.qtpl:19
		qw422016.N().S(`/></a>`)
//line templates/ad_banner.qtpl:21
	} else {
//line templates/ad_banner.qtpl:22
		if asset.IsVideo() {
//line templates/ad_banner.qtpl:22
			qw422016.N().S(`<a href="`)
//line templates/ad_banner.qtpl:23
			qw422016.N().S(urlStr)
//line templates/ad_banner.qtpl:23
			qw422016.N().S(`" target="_blank"><videoonload="u`)
//line templates/ad_banner.qtpl:24
			qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:24
			qw422016.N().S(`(1);v`)
//line templates/ad_banner.qtpl:24
			qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:24
			qw422016.N().S(`(1)"onerror="u`)
//line templates/ad_banner.qtpl:25
			qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:25
			qw422016.N().S(`(0);v`)
//line templates/ad_banner.qtpl:25
			qw422016.N().D(int(it.AdID()))
//line templates/ad_banner.qtpl:25
			qw422016.N().S(`(0)"`)
//line templates/ad_banner.qtpl:26
			if format.IsFixed() {
//line templates/ad_banner.qtpl:26
				qw422016.N().S(`width="`)
//line templates/ad_banner.qtpl:27
				qw422016.N().D(format.Width)
//line templates/ad_banner.qtpl:27
				qw422016.N().S(`" height="`)
//line templates/ad_banner.qtpl:27
				qw422016.N().D(format.Height)
//line templates/ad_banner.qtpl:27
				qw422016.N().S(`"`)
//line templates/ad_banner.qtpl:28
			}
//line templates/ad_banner.qtpl:28
			qw422016.N().S(`autoplay loop><source src="`)
//line templates/ad_banner.qtpl:29
			qw422016.N().S(asset.Path)
//line templates/ad_banner.qtpl:29
			qw422016.N().S(`" type="video/mp4"></video></a>`)
//line templates/ad_banner.qtpl:31
		} else {
//line templates/ad_banner.qtpl:31
			qw422016.N().S(`Undefined asset type`)
//line templates/ad_banner.qtpl:32
			qw422016.E().V(asset.Type)
//line templates/ad_banner.qtpl:33
		}
//line templates/ad_banner.qtpl:34
	}
//line templates/ad_banner.qtpl:35
}

//line templates/ad_banner.qtpl:35
func writeadRenderBanner(qq422016 qtio422016.Writer, resp adsource.Responser, it adsource.ResponserItem) {
//line templates/ad_banner.qtpl:35
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/ad_banner.qtpl:35
	streamadRenderBanner(qw422016, resp, it)
//line templates/ad_banner.qtpl:35
	qt422016.ReleaseWriter(qw422016)
//line templates/ad_banner.qtpl:35
}

//line templates/ad_banner.qtpl:35
func adRenderBanner(resp adsource.Responser, it adsource.ResponserItem) string {
//line templates/ad_banner.qtpl:35
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/ad_banner.qtpl:35
	writeadRenderBanner(qb422016, resp, it)
//line templates/ad_banner.qtpl:35
	qs422016 := string(qb422016.B)
//line templates/ad_banner.qtpl:35
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/ad_banner.qtpl:35
	return qs422016
//line templates/ad_banner.qtpl:35
}
