// Code generated by qtc from "ad_context.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line private/templates/ad_context.qtpl:2
package templates

//line private/templates/ad_context.qtpl:2
import (
	"github.com/geniusrabbit/adcorelib/adtype"
)

//line private/templates/ad_context.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line private/templates/ad_context.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line private/templates/ad_context.qtpl:7
func streamadRenderContext(qw422016 *qt422016.Writer, resp adtype.Responser, ad *adtype.ResponseAdItem) {
//line private/templates/ad_context.qtpl:7
	qw422016.N().S(`<h1>`)
//line private/templates/ad_context.qtpl:8
	qw422016.N().S(ad.Ad.ContentItemString("title"))
//line private/templates/ad_context.qtpl:8
	qw422016.N().S(`</h1><p>`)
//line private/templates/ad_context.qtpl:9
	qw422016.N().S(ad.Ad.ContentItemString("content"))
//line private/templates/ad_context.qtpl:9
	qw422016.N().S(`</p>`)
//line private/templates/ad_context.qtpl:10
}

//line private/templates/ad_context.qtpl:10
func writeadRenderContext(qq422016 qtio422016.Writer, resp adtype.Responser, ad *adtype.ResponseAdItem) {
//line private/templates/ad_context.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_context.qtpl:10
	streamadRenderContext(qw422016, resp, ad)
//line private/templates/ad_context.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_context.qtpl:10
}

//line private/templates/ad_context.qtpl:10
func adRenderContext(resp adtype.Responser, ad *adtype.ResponseAdItem) string {
//line private/templates/ad_context.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_context.qtpl:10
	writeadRenderContext(qb422016, resp, ad)
//line private/templates/ad_context.qtpl:10
	qs422016 := string(qb422016.B)
//line private/templates/ad_context.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_context.qtpl:10
	return qs422016
//line private/templates/ad_context.qtpl:10
}
