// Code generated by qtc from "ad_html.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line private/templates/ad_html.qtpl:2
package templates

//line private/templates/ad_html.qtpl:2
import (
	"strings"

	"geniusrabbit.dev/adcorelib/admodels/types"
	"geniusrabbit.dev/adcorelib/adtype"
)

//line private/templates/ad_html.qtpl:10
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line private/templates/ad_html.qtpl:10
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line private/templates/ad_html.qtpl:10
func StreamAdRenderRTBIFrame(qw422016 *qt422016.Writer, bidResponse adtype.Responser) {
//line private/templates/ad_html.qtpl:11
	streamadHeader(qw422016)
//line private/templates/ad_html.qtpl:12
	for _, bid := range bidResponse.Ads() {
//line private/templates/ad_html.qtpl:13
		StreamAdRenderRTBBid(qw422016, bidResponse, bid.(*adtype.ResponseBidItem))
//line private/templates/ad_html.qtpl:14
	}
//line private/templates/ad_html.qtpl:15
	streamadFooter(qw422016)
//line private/templates/ad_html.qtpl:16
}

//line private/templates/ad_html.qtpl:16
func WriteAdRenderRTBIFrame(qq422016 qtio422016.Writer, bidResponse adtype.Responser) {
//line private/templates/ad_html.qtpl:16
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:16
	StreamAdRenderRTBIFrame(qw422016, bidResponse)
//line private/templates/ad_html.qtpl:16
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:16
}

//line private/templates/ad_html.qtpl:16
func AdRenderRTBIFrame(bidResponse adtype.Responser) string {
//line private/templates/ad_html.qtpl:16
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:16
	WriteAdRenderRTBIFrame(qb422016, bidResponse)
//line private/templates/ad_html.qtpl:16
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:16
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:16
	return qs422016
//line private/templates/ad_html.qtpl:16
}

//line private/templates/ad_html.qtpl:19
func StreamAdRenderRTBBid(qw422016 *qt422016.Writer, bidResponse adtype.Responser, bid *adtype.ResponseBidItem) {
//line private/templates/ad_html.qtpl:20
	streamadPixelItem(qw422016, bid, bidResponse)
//line private/templates/ad_html.qtpl:21
	if strings.HasPrefix(bid.Bid.AdMarkup, "http://") ||
		strings.HasPrefix(bid.Bid.AdMarkup, "https://") ||
		strings.HasPrefix(bid.Bid.AdMarkup, "//") {
//line private/templates/ad_html.qtpl:23
		qw422016.N().S(`<iframe src="`)
//line private/templates/ad_html.qtpl:24
		qw422016.E().S(bid.Bid.AdMarkup)
//line private/templates/ad_html.qtpl:24
		qw422016.N().S(`"style="width:100%;height:100%;border:none"scrolling="no"allowtransparency="true"allowfullscreen="true"frameborder="0"marginheight="0"marginwidth="0"vspace="0"hspace="0"onload="u`)
//line private/templates/ad_html.qtpl:34
		qw422016.N().S(bid.Bid.ID)
//line private/templates/ad_html.qtpl:34
		qw422016.N().S(`(1);v`)
//line private/templates/ad_html.qtpl:34
		qw422016.N().S(bid.Bid.ID)
//line private/templates/ad_html.qtpl:34
		qw422016.N().S(`(1)"onerror="u`)
//line private/templates/ad_html.qtpl:35
		qw422016.N().S(bid.Bid.ID)
//line private/templates/ad_html.qtpl:35
		qw422016.N().S(`(0);v`)
//line private/templates/ad_html.qtpl:35
		qw422016.N().S(bid.Bid.ID)
//line private/templates/ad_html.qtpl:35
		qw422016.N().S(`(0)"seamless></iframe>`)
//line private/templates/ad_html.qtpl:37
	} else {
//line private/templates/ad_html.qtpl:38
		qw422016.N().S(bid.Bid.AdMarkup)
//line private/templates/ad_html.qtpl:39
	}
//line private/templates/ad_html.qtpl:40
}

//line private/templates/ad_html.qtpl:40
func WriteAdRenderRTBBid(qq422016 qtio422016.Writer, bidResponse adtype.Responser, bid *adtype.ResponseBidItem) {
//line private/templates/ad_html.qtpl:40
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:40
	StreamAdRenderRTBBid(qw422016, bidResponse, bid)
//line private/templates/ad_html.qtpl:40
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:40
}

//line private/templates/ad_html.qtpl:40
func AdRenderRTBBid(bidResponse adtype.Responser, bid *adtype.ResponseBidItem) string {
//line private/templates/ad_html.qtpl:40
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:40
	WriteAdRenderRTBBid(qb422016, bidResponse, bid)
//line private/templates/ad_html.qtpl:40
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:40
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:40
	return qs422016
//line private/templates/ad_html.qtpl:40
}

//line private/templates/ad_html.qtpl:43
func StreamAdRenderComplexIFrame(qw422016 *qt422016.Writer, resp adtype.Responser) {
//line private/templates/ad_html.qtpl:44
	streamadHeader(qw422016)
//line private/templates/ad_html.qtpl:45
	for _, ad := range resp.Ads() {
//line private/templates/ad_html.qtpl:46
		switch it := ad.(type) {
//line private/templates/ad_html.qtpl:47
		case adtype.ResponserItem:
//line private/templates/ad_html.qtpl:48
			streamadRenderOne(qw422016, resp, it)
//line private/templates/ad_html.qtpl:49
		case adtype.ResponserMultipleItem:
//line private/templates/ad_html.qtpl:50
			streamadRenderMulty(qw422016, resp, it)
//line private/templates/ad_html.qtpl:51
		default:
//line private/templates/ad_html.qtpl:51
			qw422016.N().S(`Unsupported type response type`)
//line private/templates/ad_html.qtpl:53
		}
//line private/templates/ad_html.qtpl:54
	}
//line private/templates/ad_html.qtpl:55
	streamadFooter(qw422016)
//line private/templates/ad_html.qtpl:56
}

//line private/templates/ad_html.qtpl:56
func WriteAdRenderComplexIFrame(qq422016 qtio422016.Writer, resp adtype.Responser) {
//line private/templates/ad_html.qtpl:56
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:56
	StreamAdRenderComplexIFrame(qw422016, resp)
//line private/templates/ad_html.qtpl:56
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:56
}

//line private/templates/ad_html.qtpl:56
func AdRenderComplexIFrame(resp adtype.Responser) string {
//line private/templates/ad_html.qtpl:56
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:56
	WriteAdRenderComplexIFrame(qb422016, resp)
//line private/templates/ad_html.qtpl:56
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:56
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:56
	return qs422016
//line private/templates/ad_html.qtpl:56
}

//line private/templates/ad_html.qtpl:59
func StreamAdRenderIFrame(qw422016 *qt422016.Writer, resp adtype.Responser, ad adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:60
	streamadHeader(qw422016)
//line private/templates/ad_html.qtpl:61
	streamadRenderOne(qw422016, resp, ad)
//line private/templates/ad_html.qtpl:62
	streamadFooter(qw422016)
//line private/templates/ad_html.qtpl:63
}

//line private/templates/ad_html.qtpl:63
func WriteAdRenderIFrame(qq422016 qtio422016.Writer, resp adtype.Responser, ad adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:63
	StreamAdRenderIFrame(qw422016, resp, ad)
//line private/templates/ad_html.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:63
}

//line private/templates/ad_html.qtpl:63
func AdRenderIFrame(resp adtype.Responser, ad adtype.ResponserItem) string {
//line private/templates/ad_html.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:63
	WriteAdRenderIFrame(qb422016, resp, ad)
//line private/templates/ad_html.qtpl:63
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:63
	return qs422016
//line private/templates/ad_html.qtpl:63
}

//line private/templates/ad_html.qtpl:66
func StreamAdRenderOne(qw422016 *qt422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:67
	streamadActionScript(qw422016)
//line private/templates/ad_html.qtpl:68
	streamadRenderOne(qw422016, resp, it)
//line private/templates/ad_html.qtpl:69
}

//line private/templates/ad_html.qtpl:69
func WriteAdRenderOne(qq422016 qtio422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:69
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:69
	StreamAdRenderOne(qw422016, resp, it)
//line private/templates/ad_html.qtpl:69
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:69
}

//line private/templates/ad_html.qtpl:69
func AdRenderOne(resp adtype.Responser, it adtype.ResponserItem) string {
//line private/templates/ad_html.qtpl:69
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:69
	WriteAdRenderOne(qb422016, resp, it)
//line private/templates/ad_html.qtpl:69
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:69
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:69
	return qs422016
//line private/templates/ad_html.qtpl:69
}

//line private/templates/ad_html.qtpl:72
func StreamAdRenderMulty(qw422016 *qt422016.Writer, resp adtype.Responser, it adtype.ResponserMultipleItem) {
//line private/templates/ad_html.qtpl:73
	streamadActionScript(qw422016)
//line private/templates/ad_html.qtpl:74
	streamadRenderMulty(qw422016, resp, it)
//line private/templates/ad_html.qtpl:75
}

//line private/templates/ad_html.qtpl:75
func WriteAdRenderMulty(qq422016 qtio422016.Writer, resp adtype.Responser, it adtype.ResponserMultipleItem) {
//line private/templates/ad_html.qtpl:75
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:75
	StreamAdRenderMulty(qw422016, resp, it)
//line private/templates/ad_html.qtpl:75
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:75
}

//line private/templates/ad_html.qtpl:75
func AdRenderMulty(resp adtype.Responser, it adtype.ResponserMultipleItem) string {
//line private/templates/ad_html.qtpl:75
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:75
	WriteAdRenderMulty(qb422016, resp, it)
//line private/templates/ad_html.qtpl:75
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:75
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:75
	return qs422016
//line private/templates/ad_html.qtpl:75
}

//line private/templates/ad_html.qtpl:78
func streamadRenderMulty(qw422016 *qt422016.Writer, resp adtype.Responser, it adtype.ResponserMultipleItem) {
//line private/templates/ad_html.qtpl:79
	for _, ad := range it.Ads() {
//line private/templates/ad_html.qtpl:80
		streamadRenderOne(qw422016, resp, ad)
//line private/templates/ad_html.qtpl:81
	}
//line private/templates/ad_html.qtpl:82
}

//line private/templates/ad_html.qtpl:82
func writeadRenderMulty(qq422016 qtio422016.Writer, resp adtype.Responser, it adtype.ResponserMultipleItem) {
//line private/templates/ad_html.qtpl:82
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:82
	streamadRenderMulty(qw422016, resp, it)
//line private/templates/ad_html.qtpl:82
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:82
}

//line private/templates/ad_html.qtpl:82
func adRenderMulty(resp adtype.Responser, it adtype.ResponserMultipleItem) string {
//line private/templates/ad_html.qtpl:82
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:82
	writeadRenderMulty(qb422016, resp, it)
//line private/templates/ad_html.qtpl:82
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:82
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:82
	return qs422016
//line private/templates/ad_html.qtpl:82
}

//line private/templates/ad_html.qtpl:85
func streamadRenderOne(qw422016 *qt422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:86
	streamadPixelItem(qw422016, it, resp)
//line private/templates/ad_html.qtpl:87
	/* Extract more preority AD format */

//line private/templates/ad_html.qtpl:88
	switch it.PriorityFormatType() {
//line private/templates/ad_html.qtpl:89
	case types.FormatProxyType, types.FormatBannerHTML5Type:
//line private/templates/ad_html.qtpl:90
		streamadRenderProxy(qw422016, resp, it)
//line private/templates/ad_html.qtpl:91
	case types.FormatBannerType:
//line private/templates/ad_html.qtpl:92
		streamadRenderBanner(qw422016, resp, it)
//line private/templates/ad_html.qtpl:93
	case types.FormatNativeType:
//line private/templates/ad_html.qtpl:94
		streamadRenderNative(qw422016, resp, it)
//line private/templates/ad_html.qtpl:95
	default:
//line private/templates/ad_html.qtpl:95
		qw422016.N().S(`Unsupported type:`)
//line private/templates/ad_html.qtpl:96
		qw422016.E().V(it.PriorityFormatType())
//line private/templates/ad_html.qtpl:97
	}
//line private/templates/ad_html.qtpl:98
}

//line private/templates/ad_html.qtpl:98
func writeadRenderOne(qq422016 qtio422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:98
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:98
	streamadRenderOne(qw422016, resp, it)
//line private/templates/ad_html.qtpl:98
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:98
}

//line private/templates/ad_html.qtpl:98
func adRenderOne(resp adtype.Responser, it adtype.ResponserItem) string {
//line private/templates/ad_html.qtpl:98
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:98
	writeadRenderOne(qb422016, resp, it)
//line private/templates/ad_html.qtpl:98
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:98
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:98
	return qs422016
//line private/templates/ad_html.qtpl:98
}

//line private/templates/ad_html.qtpl:101
func streamadRenderCustom(qw422016 *qt422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:101
	qw422016.N().S(`CUSTOM`)
//line private/templates/ad_html.qtpl:103
}

//line private/templates/ad_html.qtpl:103
func writeadRenderCustom(qq422016 qtio422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_html.qtpl:103
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_html.qtpl:103
	streamadRenderCustom(qw422016, resp, it)
//line private/templates/ad_html.qtpl:103
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_html.qtpl:103
}

//line private/templates/ad_html.qtpl:103
func adRenderCustom(resp adtype.Responser, it adtype.ResponserItem) string {
//line private/templates/ad_html.qtpl:103
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_html.qtpl:103
	writeadRenderCustom(qb422016, resp, it)
//line private/templates/ad_html.qtpl:103
	qs422016 := string(qb422016.B)
//line private/templates/ad_html.qtpl:103
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_html.qtpl:103
	return qs422016
//line private/templates/ad_html.qtpl:103
}
