// Code generated by qtc from "ad_native.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line private/templates/ad_native.qtpl:2
package templates

//line private/templates/ad_native.qtpl:2
import (
	"github.com/demdxx/gocast/v2"

	"geniusrabbit.dev/adcorelib/adtype"
)

//line private/templates/ad_native.qtpl:9
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line private/templates/ad_native.qtpl:9
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line private/templates/ad_native.qtpl:9
func streamadRenderNative(qw422016 *qt422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_native.qtpl:11
	urlStr := URLGen.MustClickURL(it, resp)
	asset := it.MainAsset()
	format := it.Format()
	config := format.GetConfig()

//line private/templates/ad_native.qtpl:16
	streamadRenderNativeCSS(qw422016)
//line private/templates/ad_native.qtpl:16
	qw422016.N().S(`<div class="banner horizontal"><div class="image-wrap">`)
//line private/templates/ad_native.qtpl:19
	if asset.IsImage() {
//line private/templates/ad_native.qtpl:19
		qw422016.N().S(`<script type="text/javascript">var _qPixel = new Image();_qPixel.onload = function() { u`)
//line private/templates/ad_native.qtpl:22
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:22
		qw422016.N().S(`(1);v`)
//line private/templates/ad_native.qtpl:22
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:22
		qw422016.N().S(`(1); };_qPixel.onerror = function() { u`)
//line private/templates/ad_native.qtpl:23
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:23
		qw422016.N().S(`(0);v`)
//line private/templates/ad_native.qtpl:23
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:23
		qw422016.N().S(`(0); };_qPixel.src = '`)
//line private/templates/ad_native.qtpl:24
		qw422016.N().S(asset.Path)
//line private/templates/ad_native.qtpl:24
		qw422016.N().S(`';</script><a target="_blank" href="`)
//line private/templates/ad_native.qtpl:26
		qw422016.N().S(urlStr)
//line private/templates/ad_native.qtpl:26
		qw422016.N().S(`" class="image" style="background-image: url(`)
//line private/templates/ad_native.qtpl:26
		qw422016.N().S(asset.Path)
//line private/templates/ad_native.qtpl:26
		qw422016.N().S(`);"></a>`)
//line private/templates/ad_native.qtpl:27
	} else {
//line private/templates/ad_native.qtpl:27
		qw422016.N().S(`<a target="_blank" href="`)
//line private/templates/ad_native.qtpl:28
		qw422016.N().S(urlStr)
//line private/templates/ad_native.qtpl:28
		qw422016.N().S(`" class="video"><video onload="u`)
//line private/templates/ad_native.qtpl:28
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:28
		qw422016.N().S(`(1);v`)
//line private/templates/ad_native.qtpl:28
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:28
		qw422016.N().S(`(1)"onerror="u`)
//line private/templates/ad_native.qtpl:29
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:29
		qw422016.N().S(`(0);v`)
//line private/templates/ad_native.qtpl:29
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_native.qtpl:29
		qw422016.N().S(`(0)"autoplay loop muted><source src="`)
//line private/templates/ad_native.qtpl:31
		qw422016.N().S(asset.Path)
//line private/templates/ad_native.qtpl:31
		qw422016.N().S(`" type="`)
//line private/templates/ad_native.qtpl:31
		if asset.ContentType != "" {
//line private/templates/ad_native.qtpl:31
			qw422016.N().S(asset.ContentType)
//line private/templates/ad_native.qtpl:31
		} else {
//line private/templates/ad_native.qtpl:31
			qw422016.N().S(`video/mp4`)
//line private/templates/ad_native.qtpl:31
		}
//line private/templates/ad_native.qtpl:31
		qw422016.N().S(`" />`)
//line private/templates/ad_native.qtpl:32
		for _, thumb := range asset.Thumbs {
//line private/templates/ad_native.qtpl:33
			if thumb.IsVideo() {
//line private/templates/ad_native.qtpl:33
				qw422016.N().S(`<source src="`)
//line private/templates/ad_native.qtpl:34
				qw422016.N().S(thumb.Path)
//line private/templates/ad_native.qtpl:34
				qw422016.N().S(`" type="`)
//line private/templates/ad_native.qtpl:34
				if thumb.ContentType != "" {
//line private/templates/ad_native.qtpl:34
					qw422016.N().S(thumb.ContentType)
//line private/templates/ad_native.qtpl:34
				} else {
//line private/templates/ad_native.qtpl:34
					qw422016.N().S(`video/mp4`)
//line private/templates/ad_native.qtpl:34
				}
//line private/templates/ad_native.qtpl:34
				qw422016.N().S(`" />`)
//line private/templates/ad_native.qtpl:35
			}
//line private/templates/ad_native.qtpl:36
		}
//line private/templates/ad_native.qtpl:36
		qw422016.N().S(`Your browser does not support HTML5 video.</video></a>`)
//line private/templates/ad_native.qtpl:39
	}
//line private/templates/ad_native.qtpl:39
	qw422016.N().S(`</div><div class="label">`)
//line private/templates/ad_native.qtpl:42
	for _, field := range config.Fields {
//line private/templates/ad_native.qtpl:43
		if val := it.ContentItem(field.Name); val != nil {
//line private/templates/ad_native.qtpl:44
			if vl, _ := field.Prepare(it.ContentItem(field.Name)); vl != nil {
//line private/templates/ad_native.qtpl:44
				qw422016.N().S(`<a target="_blank" href="`)
//line private/templates/ad_native.qtpl:45
				qw422016.N().S(urlStr)
//line private/templates/ad_native.qtpl:45
				qw422016.N().S(`" class="`)
//line private/templates/ad_native.qtpl:45
				qw422016.N().S(field.Name)
//line private/templates/ad_native.qtpl:45
				qw422016.N().S(`">`)
//line private/templates/ad_native.qtpl:46
				qw422016.N().S(gocast.ToString(vl))
//line private/templates/ad_native.qtpl:46
				qw422016.N().S(`</a>`)
//line private/templates/ad_native.qtpl:48
			}
//line private/templates/ad_native.qtpl:49
		}
//line private/templates/ad_native.qtpl:50
	}
//line private/templates/ad_native.qtpl:50
	qw422016.N().S(`</div></div>`)
//line private/templates/ad_native.qtpl:53
}

//line private/templates/ad_native.qtpl:53
func writeadRenderNative(qq422016 qtio422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_native.qtpl:53
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_native.qtpl:53
	streamadRenderNative(qw422016, resp, it)
//line private/templates/ad_native.qtpl:53
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_native.qtpl:53
}

//line private/templates/ad_native.qtpl:53
func adRenderNative(resp adtype.Responser, it adtype.ResponserItem) string {
//line private/templates/ad_native.qtpl:53
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_native.qtpl:53
	writeadRenderNative(qb422016, resp, it)
//line private/templates/ad_native.qtpl:53
	qs422016 := string(qb422016.B)
//line private/templates/ad_native.qtpl:53
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_native.qtpl:53
	return qs422016
//line private/templates/ad_native.qtpl:53
}

//line private/templates/ad_native.qtpl:56
func streamadRenderNativeCSS(qw422016 *qt422016.Writer) {
//line private/templates/ad_native.qtpl:56
	qw422016.N().S(`<style type="text/css">html, body {padding: 0;margin: 0;height: 100%;box-sizing: border-box;}.banner {font-family: Arial,Helvetica,sans-serif;background: #fff;overflow: hidden;height: 100%;position: relative;padding-bottom: 83px;-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;}.banner .label {padding: 2px 5px;box-sizing: border-box;height: 83px;position: absolute;bottom: 0;left: 0;right: 0;}.banner .label a {text-decoration: none!important;word-wrap: break-word;overflow: hidden;background-image: none;-webkit-box-sizing: content-box;-moz-box-sizing: content-box;box-sizing: content-box;display: block;}.banner .label a:hover {color: #35327b;}.banner .label .title,.banner .label .description {font-size: 14px;font-weight: 400;line-height: 1.3em;max-height: 65px;color: #000;}.banner .label .brand {font-size: 11px;font-weight: 700;line-height: 1em;max-height: 22px;color: #999;padding: 3px 0 0;}.banner .brandname {font-size: 11px;font-weight: 700;line-height: 1em;max-height: 22px;color: #999;padding: 3px 0 0;}.banner .phone {font-size: 11px;font-weight: 700;line-height: 1em;max-height: 22px;color: #699;padding: 3px 0 0;}.banner .image {border-style: none;-moz-border-radius: 0;-webkit-border-radius: 0;border-radius: 0;border-width: 0;background-color: #eee;height: 100%;-webkit-box-sizing: border-box;-moz-box-sizing: border-box;box-sizing: border-box;background-size: cover;background-position: center center;background-repeat: no-repeat;display: block;margin: 0;}@media screen and (min-aspect-ratio: 10/7) {.banner .image{width: 40%;float: left;}.banner .label{width: 60%;float: left;position: static;}.banner {padding: 0;}}/* === horizontal orientation === */.banner.horizontal {padding: 0;}.banner.horizontal .image{width: 40%;float: left;}.banner.horizontal .label{width: 60%;float: left;position: static;}</style>`)
//line private/templates/ad_native.qtpl:173
}

//line private/templates/ad_native.qtpl:173
func writeadRenderNativeCSS(qq422016 qtio422016.Writer) {
//line private/templates/ad_native.qtpl:173
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_native.qtpl:173
	streamadRenderNativeCSS(qw422016)
//line private/templates/ad_native.qtpl:173
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_native.qtpl:173
}

//line private/templates/ad_native.qtpl:173
func adRenderNativeCSS() string {
//line private/templates/ad_native.qtpl:173
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_native.qtpl:173
	writeadRenderNativeCSS(qb422016)
//line private/templates/ad_native.qtpl:173
	qs422016 := string(qb422016.B)
//line private/templates/ad_native.qtpl:173
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_native.qtpl:173
	return qs422016
//line private/templates/ad_native.qtpl:173
}
