// Code generated by qtc from "ad_proxy.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line private/templates/ad_proxy.qtpl:2
package templates

//line private/templates/ad_proxy.qtpl:2
import (
	"github.com/geniusrabbit/adcorelib/adtype"
)

//line private/templates/ad_proxy.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line private/templates/ad_proxy.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line private/templates/ad_proxy.qtpl:7
func streamadRenderProxy(qw422016 *qt422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_proxy.qtpl:8
	if url := it.ContentItemString("iframe_url"); len(url) > 0 {
//line private/templates/ad_proxy.qtpl:8
		qw422016.N().S(`<iframe src="`)
//line private/templates/ad_proxy.qtpl:9
		qw422016.E().S(url)
//line private/templates/ad_proxy.qtpl:9
		qw422016.N().S(`"style="width:100%;height:100%;border:none"scrolling="no"allowtransparency="true"allowfullscreen="true"frameborder="0"marginheight="0"marginwidth="0"vspace="0"hspace="0"onload="u`)
//line private/templates/ad_proxy.qtpl:19
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_proxy.qtpl:19
		qw422016.N().S(`(1);v`)
//line private/templates/ad_proxy.qtpl:19
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_proxy.qtpl:19
		qw422016.N().S(`(1)"onerror="u`)
//line private/templates/ad_proxy.qtpl:20
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_proxy.qtpl:20
		qw422016.N().S(`(0);v`)
//line private/templates/ad_proxy.qtpl:20
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_proxy.qtpl:20
		qw422016.N().S(`(0)"seamless></iframe>`)
//line private/templates/ad_proxy.qtpl:22
	} else {
//line private/templates/ad_proxy.qtpl:22
		qw422016.N().S(`<script type="text/javascript">u`)
//line private/templates/ad_proxy.qtpl:23
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_proxy.qtpl:23
		qw422016.N().S(`(1);v`)
//line private/templates/ad_proxy.qtpl:23
		qw422016.N().D(int(it.AdID()))
//line private/templates/ad_proxy.qtpl:23
		qw422016.N().S(`(1);</script>`)
//line private/templates/ad_proxy.qtpl:24
		qw422016.N().S(it.ContentItemString("content"))
//line private/templates/ad_proxy.qtpl:25
	}
//line private/templates/ad_proxy.qtpl:26
}

//line private/templates/ad_proxy.qtpl:26
func writeadRenderProxy(qq422016 qtio422016.Writer, resp adtype.Responser, it adtype.ResponserItem) {
//line private/templates/ad_proxy.qtpl:26
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_proxy.qtpl:26
	streamadRenderProxy(qw422016, resp, it)
//line private/templates/ad_proxy.qtpl:26
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_proxy.qtpl:26
}

//line private/templates/ad_proxy.qtpl:26
func adRenderProxy(resp adtype.Responser, it adtype.ResponserItem) string {
//line private/templates/ad_proxy.qtpl:26
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_proxy.qtpl:26
	writeadRenderProxy(qb422016, resp, it)
//line private/templates/ad_proxy.qtpl:26
	qs422016 := string(qb422016.B)
//line private/templates/ad_proxy.qtpl:26
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_proxy.qtpl:26
	return qs422016
//line private/templates/ad_proxy.qtpl:26
}

//line private/templates/ad_proxy.qtpl:29
func streamadDefault(qw422016 *qt422016.Writer, spotID int, tag string) {
//line private/templates/ad_proxy.qtpl:30
	streamadHeader(qw422016)
//line private/templates/ad_proxy.qtpl:31
	streamadPixel(qw422016, 0, spotID, 0, tag)
//line private/templates/ad_proxy.qtpl:31
	qw422016.N().S(`<iframe src="//cdn.gr.com/page/error_banner.html"style="width:100%;height:100%;border:none"scrolling="no"allowtransparency="true"allowfullscreen="true"frameborder="0"marginheight="0"marginwidth="0"vspace="0"hspace="0"onload="u0(1);v0(1)"onerror="u0(0);v0(0)"seamless></iframe>`)
//line private/templates/ad_proxy.qtpl:45
	streamadFooter(qw422016)
//line private/templates/ad_proxy.qtpl:46
}

//line private/templates/ad_proxy.qtpl:46
func writeadDefault(qq422016 qtio422016.Writer, spotID int, tag string) {
//line private/templates/ad_proxy.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line private/templates/ad_proxy.qtpl:46
	streamadDefault(qw422016, spotID, tag)
//line private/templates/ad_proxy.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line private/templates/ad_proxy.qtpl:46
}

//line private/templates/ad_proxy.qtpl:46
func adDefault(spotID int, tag string) string {
//line private/templates/ad_proxy.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line private/templates/ad_proxy.qtpl:46
	writeadDefault(qb422016, spotID, tag)
//line private/templates/ad_proxy.qtpl:46
	qs422016 := string(qb422016.B)
//line private/templates/ad_proxy.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line private/templates/ad_proxy.qtpl:46
	return qs422016
//line private/templates/ad_proxy.qtpl:46
}
